/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contabilidad;

import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JLabel;
import java.awt.Graphics;
import javax.swing.JTextField;
import javax.swing.JFrame;
import java.awt.Dimension;
import javax.swing.JPanel;
import java.awt.Rectangle;
import java.awt.Color;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Font;
import javax.swing.SwingConstants;
import java.awt.Insets;
import java.awt.Graphics;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Sahsil
 */
public class Sistema extends javax.swing.JFrame {
    
    
    int start=0;
    ArrayList<Entrada> listaEntrada=new ArrayList<Entrada>();//ArrayList para guardar todos los objetos del tipo Entrada que se hagan en la interfaz
    ArrayList<Salida> listaSalida=new ArrayList<Salida>();//ArrayList para guardar todos los objetos del tipo Salida que se hagan en la interfaz
    public Sistema() {
        initComponents();
        jPanel6.setVisible(false);//Poniendo invisibles todos los paneles para que asi vayan mostrandose de acuerdo a como el usuario vaya avanzando
        jPExit.setVisible(false);
        jPEntry.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jBmove = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPEntry = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTEnName = new javax.swing.JTextField();
        jTEnCant = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jBEntry = new javax.swing.JButton();
        jPExit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTExName = new javax.swing.JTextField();
        jTExCant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jBRemEx = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBRemEn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jBCrearDoc = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBmove.setText("Agregar una Entrada");
        jBmove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmoveActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre del Movimiento");

        jLabel6.setText("Cantidad ");

        jLabel7.setText("$");

        jBEntry.setText("Registrar");
        jBEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEntryLayout = new javax.swing.GroupLayout(jPEntry);
        jPEntry.setLayout(jPEntryLayout);
        jPEntryLayout.setHorizontalGroup(
            jPEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEntryLayout.createSequentialGroup()
                .addGroup(jPEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEntryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addGroup(jPEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTEnName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTEnCant, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPEntryLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jBEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPEntryLayout.setVerticalGroup(
            jPEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEntryLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTEnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTEnCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel2.setText("Nombre del Movimiento");

        jLabel3.setText("Cantidad ");

        jLabel4.setText("$");

        jBExit.setText("Registrar");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPExitLayout = new javax.swing.GroupLayout(jPExit);
        jPExit.setLayout(jPExitLayout);
        jPExitLayout.setHorizontalGroup(
            jPExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPExitLayout.createSequentialGroup()
                .addGroup(jPExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPExitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addGroup(jPExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTExName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTExCant, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPExitLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPExitLayout.setVerticalGroup(
            jPExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPExitLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTExName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTExCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 52, Short.MAX_VALUE))
        );

        jTable2.setBackground(new java.awt.Color(0, 255, 153));
        jTable2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Especificación", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setInheritsPopupMenu(true);
        jScrollPane2.setViewportView(jTable2);

        jBRemEx.setText("Remover");
        jBRemEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemExActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 225, Short.MAX_VALUE)
                        .addComponent(jBRemEx)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBRemEx)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTable1.setBackground(new java.awt.Color(204, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Especificación", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(jTable1);

        jBRemEn.setText("Remover");
        jBRemEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemEnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBRemEn)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBRemEn)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1.setText("Agregar una Salida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar Saldo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jBCrearDoc.setText("Crear Documento");
        jBCrearDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jBmove, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jBCrearDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209)
                .addComponent(salir)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBmove, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(jBCrearDoc, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBmoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmoveActionPerformed
        
            jPanel6.setVisible(true);//al oprimir este boton se hacen visibles los paneles necesarios para guardar una nueva Entrada
            jPEntry.setVisible(true);
            
        
            
    }//GEN-LAST:event_jBmoveActionPerformed

    private void jBEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntryActionPerformed

        Entrada entrada=new Entrada(jTEnName.getText(),jTEnCant.getText());
        listaEntrada.add(entrada);//Se crea nuevo objeto del tipo Entrada con las caracteristicas que se le dieron y se guarda en el ArrayList
        
        mostrarE();//Se activa el metodo mostrarE, que logra que se muestre en una tabla los objetos del tipo Entrada que se deseen
    }//GEN-LAST:event_jBEntryActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed

        
        Salida salida=new Salida(jTExName.getText(),jTExCant.getText());
        listaSalida.add(salida);//Se crea nuevo objeto del tipo Salida con las caracteristicas que se le dieron y se guarda en el ArrayList
        
        mostrarEx();//Se activa el metodo mostrarEx, que logra que se muestre en una tabla los objetos del tipo Salida que se deseen
    }//GEN-LAST:event_jBExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel6.setVisible(true);//al oprimir este boton se hacen visibles los paneles necesarios para guardar una nueva Salida
        jPExit.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBRemEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemEnActionPerformed
        listaEntrada.remove(listaEntrada.size()-1);
        borrarE(); //Borrar último objeto del tipo Entrada del ArrayList
    }//GEN-LAST:event_jBRemEnActionPerformed

    private void jBRemExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemExActionPerformed
        listaSalida.remove(listaSalida.size()-1);
        borrarEx(); //Borrar último objeto del tipo Entrada del ArrayList
    }//GEN-LAST:event_jBRemExActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose(); //Salir de la pantalla
    }//GEN-LAST:event_salirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mostrarSaldo();//Muestra el saldo que queda restando las Salidas de las Entradas
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBCrearDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearDocActionPerformed
        try {
            crearArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
        }//Crea un archivo con los datos que se guardaron
    }//GEN-LAST:event_jBCrearDocActionPerformed
        
        public void mostrarE()
        {
            jPanel4.setVisible(true);//muestra panel donde se encuentra la tabla de Entradas
            String matrizE[][]=new String [listaEntrada.size()][2];//Convierte el ArrayList en una matriz para mas facilidad
            for(int i=0; i<listaEntrada.size();i++)//Llena la matriz con los datos del ArrayList
            {
                matrizE[i][0]=listaEntrada.get(i).getName();
                matrizE[i][1]=listaEntrada.get(i).getCantidad();
            }
            
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matrizE,//imprime la tabla con los datos guardados en la matriz
            new String [] {
                "Especificación", "Cantidad"
            }
            ));
        }
         public void borrarE() //Hace lo mismo que el metodo anterior, solo que cuando se llama este metodo, se borra el ultimo objeto creado del tipo Entrada, borrando asi el ultimo registro
        {
            jPanel4.setVisible(true);
            String matrizE[][]=new String [listaEntrada.size()][2];
            for(int i=0; i<listaEntrada.size();i++)
            {
                matrizE[i][0]=listaEntrada.get(i).getName();
                matrizE[i][1]=listaEntrada.get(i).getCantidad();  
            }
            
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matrizE,
            new String [] {
                "Especificación", "Cantidad"
            }
            ));
        }
        public void mostrarEx()//Hace lo mismo que el metodo para mostrar Entradas, solo que este con salidas
        {
            jPanel5.setVisible(true);
            String matriz[][]=new String [listaSalida.size()][2];
            for(int i=0; i<listaSalida.size();i++)
            {
                matriz[i][0]=listaSalida.get(i).getName();
                matriz[i][1]=listaSalida.get(i).getCantidad();
            }
            
            jTable2.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Especificación", "Cantidad"
            }
        )); 
        }
        public void borrarEx()//Hace lo mismo que el metodo anterior, solo que cuando se llama este metodo, se borra el ultimo objeto creado del tipo Salida, borrando asi el ultimo registro
        {
            jPanel5.setVisible(true);
            String matriz[][]=new String [listaSalida.size()][2];
            for(int i=0; i<listaSalida.size();i++)
            {
                matriz[i][0]=listaSalida.get(i).getName();
                matriz[i][1]=listaSalida.get(i).getCantidad();
            }
            
            jTable2.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Especificación", "Cantidad"
            }
        )); 
        }
        public void mostrarSaldo()//metodo que convierte los strings del dinero en doubles para poder manejarlos y asi sacar un saldo
        {
            double totalSaldo;
            
            double sumaEnt=0;
            double matrixEnt[]=new double[listaEntrada.size()];
            String matriz[][]=new String [listaEntrada.size()][2];
            for(int i=0; i<listaEntrada.size();i++)
            {
                matriz[i][0]=listaEntrada.get(i).getName();
                matriz[i][1]=listaEntrada.get(i).getCantidad();
            }    
            for(int i=0;i<listaEntrada.size();i++)
                {
                    double k=Double.parseDouble(matriz[i][1]);//convierte cada string de las cantidades de las Entradas a Doubles
                    matrixEnt[i]=k;
                    sumaEnt=matrixEnt[i]+sumaEnt;//Suma todas las cantidades de las Entradas y las guarda en una variable
                }
            
            
            double sumaEx=0;
            double matrixEx[]=new double[listaSalida.size()];
            String matrizEx[][]=new String [listaSalida.size()][2];
            for(int i=0; i<listaSalida.size();i++)
            {
                matrizEx[i][0]=listaSalida.get(i).getName();
                matrizEx[i][1]=listaSalida.get(i).getCantidad();
            }    
            for(int i=0;i<listaSalida.size();i++)
                {
                    double e=Double.parseDouble(matrizEx[i][1]);//convierte cada string de las cantidades de las Salidas a Doubles
                    matrixEx[i]=e;
                    sumaEx=matrixEx[i]+sumaEx;//Suma todas las cantidades de las Salidas y las guarda en una variable
                }
            
            totalSaldo=sumaEnt-sumaEx;//Variable que muestra el saldo
            System.out.println(totalSaldo);//Mostrar el saldo en la consola
            String total2 = String.valueOf(totalSaldo);//Convertir el saldo en String para poder mostrarlo en Frame
            JOptionPane.showMessageDialog(null, total2);//MOstrar saldo en una nueva pantalla
            
            
            

        }
        
        public void crearArchivo() throws IOException//crea archivo con el saldo de la empresa
        {
            double totalSaldo;
            
            double sumaEnt=0;
            double matrixEnt[]=new double[listaEntrada.size()];
            String matriz[][]=new String [listaEntrada.size()][2];
            for(int i=0; i<listaEntrada.size();i++)
            {
                matriz[i][0]=listaEntrada.get(i).getName();
                matriz[i][1]=listaEntrada.get(i).getCantidad();
            }    
            for(int i=0;i<listaEntrada.size();i++)
                {
                    double k=Double.parseDouble(matriz[i][1]);//convierte cada string de las cantidades de las Entradas a Doubles
                    matrixEnt[i]=k;
                    sumaEnt=matrixEnt[i]+sumaEnt;//Suma todas las cantidades de las Entradas y las guarda en una variable
                }
            
            
            double sumaEx=0;
            double matrixEx[]=new double[listaSalida.size()];
            String matrizEx[][]=new String [listaSalida.size()][2];
            for(int i=0; i<listaSalida.size();i++)
            {
                matrizEx[i][0]=listaSalida.get(i).getName();
                matrizEx[i][1]=listaSalida.get(i).getCantidad();
            }    
            for(int i=0;i<listaSalida.size();i++)
                {
                    double e=Double.parseDouble(matrizEx[i][1]);//convierte cada string de las cantidades de las Salidas a Doubles
                    matrixEx[i]=e;
                    sumaEx=matrixEx[i]+sumaEx;//Suma todas las cantidades de las Salidas y las guarda en una variable
                }
            
            totalSaldo=sumaEnt-sumaEx;//Variable que muestra el saldo
            String total2 = String.valueOf(totalSaldo);//Convertir el saldo en String para poder mostrarlo en Frame
            
            
            File file = new File("miarchivo.txt"); //Crear el archivo
            if (!file.exists())
            {
                try
                {
                    file.createNewFile();
                    System.out.println(file.getName()+ " ha sido creado");
                    
                }catch(IOException ex)
                {
                    ex.printStackTrace();
                }
            }
            BufferedWriter writer = null;
            
            
            
            //llenar el archivo con los datos de las matrices
                try
                {
                    writer = new BufferedWriter(new FileWriter(file));
                    writer.write("El saldo de la empresa es de $"+total2);
                }catch (Exception e) 
                {
                    e.printStackTrace();
                }finally{
            
            
                
            
            
            
                try {
                    // Close the writer regardless of what happens...
                    writer.close();
                } catch (Exception e) {
                }
                }
                
        }       
         
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCrearDoc;
    private javax.swing.JButton jBEntry;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBRemEn;
    private javax.swing.JButton jBRemEx;
    private javax.swing.JButton jBmove;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPEntry;
    private javax.swing.JPanel jPExit;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTEnCant;
    private javax.swing.JTextField jTEnName;
    private javax.swing.JTextField jTExCant;
    private javax.swing.JTextField jTExName;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
